name: Newt
version: 2025.10.2
slug: newt
description: Tunneling client to connect Home Assistant to Pangolin.
url: https://github.com/elcajon-dev/addon-newt
codenotary: codenotary@elcajon.dev
startup: services
init: false
arch:
- aarch64
- amd64
- armv7
schema:
  pangolin_endpoint: str
  newt_id: str
  newt_secret: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/elcajon-dev/newt/{arch}
